name: Build and Push to ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: 544234170512.dkr.ecr.us-east-1.amazonaws.com/springboot-demo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    #please add mvn clean package command here
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests

    
    - name: Build Docker image
      run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=springboot-demo

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::544234170512:role/GithubRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag springboot-demo:latest ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker push ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

    - name: Clean up
      if: always()
      run: |
        docker rmi ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker rmi springboot-demo:latest